Repository oruscam/RIVeR, pull requests merged in 2025-07, with the labels that each got.

#83 Add Italian, Portuguese, and German translations + Update README (issu #80)
  gui/src/components/LanguageSelector.tsx
  gui/src/components/components.css
  gui/src/translations/de/global.json
  gui/src/translations/en/global.json
  gui/src/translations/es/global.json
  gui/src/translations/fr/global.json
  gui/src/translations/i18n.js
  gui/src/translations/it/global.json
  gui/src/translations/pt/global.json
  readme.md
Labels: enhancement, Language, release/3.2.0

#90 Enhancement/issue 77 wcmp metadata keys
  gui/electron/ipcMainHandlers/firstFrame.ts
  gui/electron/ipcMainHandlers/index.ts
  gui/electron/ipcMainHandlers/saveReportHtml.ts
  gui/electron/ipcMainHandlers/setProjectDetails.ts
  gui/electron/ipcMainHandlers/setProjectMetadata.ts
  gui/electron/ipcMainHandlers/utils/saveProjectMetadata.ts
  gui/electron/main.ts
  gui/src/components/Forms/FormReport.tsx
  gui/src/hooks/useProjectSlice.ts
  gui/src/pages/Report.tsx
Labels: enhancement

#91 fix xsections measured/interpolated values
  gui/electron/ipcMainHandlers/getResultData.ts
  gui/electron/ipcMainHandlers/utils/transformCrossSectionsData.ts
  gui/src/components/Report/ReportSection.tsx
  gui/src/helpers/adapterCrossSections.ts
  gui/src/hooks/useDataSlice.ts
Labels: bug

#93 Change default directory in load project
  gui/electron/ipcMainHandlers/calculate3dRectification.ts
  gui/electron/ipcMainHandlers/createFolderStructure.ts
  gui/electron/ipcMainHandlers/createMaskAndBbox.ts
  gui/electron/ipcMainHandlers/firstFrame.ts
  gui/electron/ipcMainHandlers/getIpcamImages.ts
  gui/electron/ipcMainHandlers/getQuiver.ts
  gui/electron/ipcMainHandlers/initProject.ts
  gui/electron/ipcMainHandlers/interfaces.ts
  gui/electron/ipcMainHandlers/loadProject.ts
  gui/electron/ipcMainHandlers/saveReportHtml.ts
  gui/electron/ipcMainHandlers/setControlPoints.ts
  gui/electron/ipcMainHandlers/setPixelSize.ts
  gui/electron/ipcMainHandlers/setSections.ts
  gui/electron/ipcMainHandlers/utils/createMatrix.ts
  gui/electron/main.ts
Labels: enhancement

#94 Add copy to clipboard talbe in tsv format
  gui/package-lock.json
  gui/package.json
  gui/src/assets/icons/clipboard.svg
  gui/src/assets/icons/icons.ts
  gui/src/components/Clipboard.tsx
  gui/src/components/Grid.tsx
  gui/src/components/components.css
  gui/src/components/index.ts
  gui/yarn.lock
Labels: enhancement

#87 Speed-up PIV pipeline: pyFFTW, single-load ROI, parallel chunks
  pyproject.toml
  requirements.txt
  river/core/matlab_smoothn.py
  river/core/piv_fftmulti.py
  river/core/piv_loop.py
  river/core/piv_pipeline.py
Labels: enhancement, release/3.2.0

#101 Update changelog for 3.2.0
  CHANGELOG.md
Labels: documentation
